[build]
builder = "static"
buildCommand = "npm install -g @angular/cli && npm install && ng build --configuration production"
publishDir = "dist/The-Lottery-Djinni"

[deploy]
startCommand = ""
healthcheckPath = "/"
restartPolicyType = "never"

[static]
directory = "dist/The-Lottery-Djinni"
