# railway.toml
[build]
# Tell Railway to use the StaticFile builder
builder = "staticfile"

# No build step on Railway — you build locally
command = "echo 'skipping build on Railway'"

[staticfile]
# point this at your locally built Angular output
directory = "dist/The-Lottery-Djinni"
